import { Employee, DashboardStats, Department, Project, Role } from './types'

export const MOCK_DEPARTMENTS: Department[] = [
  { id: '1',  departmentCode: 'ENG', departmentName: 'Engineering', location: 'HQ', employees: [] },
  { id: '2',  departmentCode: 'PRD', departmentName: 'Product',     location: 'HQ', employees: [] },
  { id: '3',  departmentCode: 'DES', departmentName: 'Design',      location: 'HQ', employees: [] },
  { id: '4',  departmentCode: 'MKT', departmentName: 'Marketing',   location: 'HQ', employees: [] },
  { id: '5',  departmentCode: 'SAL', departmentName: 'Sales',       location: 'HQ', employees: [] },
  { id: '6',  departmentCode: 'OPS', departmentName: 'Operations',  location: 'HQ', employees: [] },
  { id: '7',  departmentCode: 'FIN', departmentName: 'Finance',     location: 'HQ', employees: [] },
  { id: '8',  departmentCode: 'HR',  departmentName: 'HR',          location: 'HQ', employees: [] },
  { id: '9',  departmentCode: 'LEG', departmentName: 'Legal',       location: 'HQ', employees: [] },
  { id: '10', departmentCode: 'SUP', departmentName: 'Support',     location: 'HQ', employees: [] },
]

export const MOCK_PROJECTS: Project[] = [
  { id: '1', projectCode: 'PROJ-001', projectName: 'ARCADE Platform',   startDate: '2024-01-01', budget: 500000 },
  { id: '2', projectCode: 'PROJ-002', projectName: 'Mobile App',        startDate: '2024-03-01', budget: 200000 },
  { id: '3', projectCode: 'PROJ-003', projectName: 'Data Pipeline',     startDate: '2024-06-01', budget: 150000 },
  { id: '4', projectCode: 'PROJ-004', projectName: 'API Gateway',       startDate: '2024-02-01', budget: 100000 },
  { id: '5', projectCode: 'PROJ-005', projectName: 'Analytics Engine',  startDate: '2024-04-01', budget: 300000 },
]

export const MOCK_ROLES: Role[] = [
  { id: '1', roleCode: 'ADMIN',    roleName: 'Admin',             description: 'Full access' },
  { id: '2', roleCode: 'MANAGER',  roleName: 'Manager',           description: 'Team management' },
  { id: '3', roleCode: 'EMPLOYEE', roleName: 'Employee',          description: 'Standard access' },
  { id: '4', roleCode: 'LEAD',     roleName: 'Tech Lead',         description: 'Technical leadership' },
  { id: '5', roleCode: 'INTERN',   roleName: 'Intern',            description: 'Limited access' },
]

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: '1', employeeCode: 'EMP-001',
    firstName: 'Alex', lastName: 'Chen', fullName: 'Alex Chen',
    email: 'alex.chen@arcade.ai', phoneNumber: '+1 (555) 234-5678',
    salary: 185000, joiningDate: '2021-03-15', status: 'ACTIVE',
    department: MOCK_DEPARTMENTS[0]!,
    address: { id: '1', houseNumber: '42', street: 'Tech Blvd', city: 'San Francisco', state: 'CA', country: 'USA', zipCode: '94102' },
    projects: [MOCK_PROJECTS[0]!, MOCK_PROJECTS[3]!],
    roles: [MOCK_ROLES[0]!],
  },
  {
    id: '2', employeeCode: 'EMP-002',
    firstName: 'Sarah', lastName: 'Mitchell', fullName: 'Sarah Mitchell',
    email: 'sarah.m@arcade.ai', phoneNumber: '+1 (555) 345-6789',
    salary: 165000, joiningDate: '2021-06-01', status: 'ACTIVE',
    department: MOCK_DEPARTMENTS[1]!,
    address: { id: '2', houseNumber: '15', street: 'Market St', city: 'San Francisco', state: 'CA', country: 'USA', zipCode: '94103' },
    projects: [MOCK_PROJECTS[0]!],
    roles: [MOCK_ROLES[1]!],
  },
  {
    id: '3', employeeCode: 'EMP-003',
    firstName: 'Marcus', lastName: 'Johnson', fullName: 'Marcus Johnson',
    email: 'marcus.j@arcade.ai', phoneNumber: '+1 (555) 456-7890',
    salary: 155000, joiningDate: '2022-01-10', status: 'REMOTE',
    department: MOCK_DEPARTMENTS[0]!,
    address: { id: '3', houseNumber: '8', street: 'Oak Ave', city: 'Austin', state: 'TX', country: 'USA', zipCode: '73301' },
    projects: [MOCK_PROJECTS[2]!, MOCK_PROJECTS[3]!],
    roles: [MOCK_ROLES[2]!],
  },
  {
    id: '4', employeeCode: 'EMP-004',
    firstName: 'Priya', lastName: 'Patel', fullName: 'Priya Patel',
    email: 'priya.p@arcade.ai', phoneNumber: '+1 (555) 567-8901',
    salary: 145000, joiningDate: '2021-09-20', status: 'ACTIVE',
    department: MOCK_DEPARTMENTS[2]!,
    address: { id: '4', houseNumber: '22', street: 'Design St', city: 'New York', state: 'NY', country: 'USA', zipCode: '10001' },
    projects: [MOCK_PROJECTS[1]!],
    roles: [MOCK_ROLES[3]!],
  },
  {
    id: '5', employeeCode: 'EMP-005',
    firstName: 'David', lastName: 'Kim', fullName: 'David Kim',
    email: 'david.k@arcade.ai', phoneNumber: '+1 (555) 678-9012',
    salary: 200000, joiningDate: '2020-07-15', status: 'ACTIVE',
    department: MOCK_DEPARTMENTS[0]!,
    address: { id: '5', houseNumber: '100', street: 'Mission St', city: 'San Francisco', state: 'CA', country: 'USA', zipCode: '94105' },
    projects: [MOCK_PROJECTS[0]!, MOCK_PROJECTS[4]!],
    roles: [MOCK_ROLES[1]!],
  },
  {
    id: '6', employeeCode: 'EMP-006',
    firstName: 'Elena', lastName: 'Rodriguez', fullName: 'Elena Rodriguez',
    email: 'elena.r@arcade.ai', phoneNumber: '+1 (555) 789-0123',
    salary: 130000, joiningDate: '2022-04-01', status: 'ACTIVE',
    department: MOCK_DEPARTMENTS[3]!,
    address: { id: '6', houseNumber: '55', street: 'Broadway', city: 'New York', state: 'NY', country: 'USA', zipCode: '10002' },
    projects: [MOCK_PROJECTS[1]!],
    roles: [MOCK_ROLES[2]!],
  },
  {
    id: '7', employeeCode: 'EMP-007',
    firstName: 'James', lastName: 'Wilson', fullName: 'James Wilson',
    email: 'james.w@arcade.ai', phoneNumber: '+1 (555) 890-1234',
    salary: 120000, joiningDate: '2022-08-15', status: 'ON_LEAVE',
    department: MOCK_DEPARTMENTS[4]!,
    address: { id: '7', houseNumber: '77', street: 'Commerce Ave', city: 'Chicago', state: 'IL', country: 'USA', zipCode: '60601' },
    projects: [],
    roles: [MOCK_ROLES[2]!],
  },
  {
    id: '8', employeeCode: 'EMP-008',
    firstName: 'Yuki', lastName: 'Tanaka', fullName: 'Yuki Tanaka',
    email: 'yuki.t@arcade.ai', phoneNumber: '+1 (555) 901-2345',
    salary: 140000, joiningDate: '2023-02-06', status: 'ACTIVE',
    department: MOCK_DEPARTMENTS[0]!,
    address: { id: '8', houseNumber: '3', street: 'Pine St', city: 'Seattle', state: 'WA', country: 'USA', zipCode: '98101' },
    projects: [MOCK_PROJECTS[2]!],
    roles: [MOCK_ROLES[2]!],
  },
  {
    id: '9', employeeCode: 'EMP-009',
    firstName: 'Omar', lastName: 'Hassan', fullName: 'Omar Hassan',
    email: 'omar.h@arcade.ai', phoneNumber: '+1 (555) 012-3456',
    salary: 125000, joiningDate: '2022-11-01', status: 'ACTIVE',
    department: MOCK_DEPARTMENTS[6]!,
    address: { id: '9', houseNumber: '12', street: 'Finance Blvd', city: 'Boston', state: 'MA', country: 'USA', zipCode: '02101' },
    projects: [MOCK_PROJECTS[4]!],
    roles: [MOCK_ROLES[2]!],
  },
  {
    id: '10', employeeCode: 'EMP-010',
    firstName: 'Aria', lastName: 'Foster', fullName: 'Aria Foster',
    email: 'aria.f@arcade.ai', phoneNumber: '+1 (555) 123-4567',
    salary: 110000, joiningDate: '2021-12-01', status: 'ACTIVE',
    department: MOCK_DEPARTMENTS[7]!,
    address: { id: '10', houseNumber: '9', street: 'HR Lane', city: 'Denver', state: 'CO', country: 'USA', zipCode: '80201' },
    projects: [],
    roles: [MOCK_ROLES[1]!],
  },
  {
    id: '11', employeeCode: 'EMP-011',
    firstName: 'Lucas', lastName: 'Oliveira', fullName: 'Lucas Oliveira',
    email: 'lucas.o@arcade.ai', phoneNumber: '+1 (555) 234-5670',
    salary: 220000, joiningDate: '2020-02-10', status: 'ACTIVE',
    department: MOCK_DEPARTMENTS[0]!,
    address: { id: '11', houseNumber: '200', street: 'Engineering Way', city: 'San Francisco', state: 'CA', country: 'USA', zipCode: '94107' },
    projects: [MOCK_PROJECTS[0]!, MOCK_PROJECTS[2]!, MOCK_PROJECTS[4]!],
    roles: [MOCK_ROLES[3]!],
  },
  {
    id: '12', employeeCode: 'EMP-012',
    firstName: 'Nina', lastName: 'Williams', fullName: 'Nina Williams',
    email: 'nina.w@arcade.ai', phoneNumber: '+1 (555) 345-6780',
    salary: 135000, joiningDate: '2021-05-15', status: 'REMOTE',
    department: MOCK_DEPARTMENTS[5]!,
    address: { id: '12', houseNumber: '45', street: 'Ops Center Dr', city: 'Phoenix', state: 'AZ', country: 'USA', zipCode: '85001' },
    projects: [MOCK_PROJECTS[3]!],
    roles: [MOCK_ROLES[2]!],
  },
]

// Keep old DEPARTMENTS string array for backward compat (used in some places)
export const DEPARTMENTS = MOCK_DEPARTMENTS.map((d) => d.departmentName)

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalEmployees: 248,
  activeEmployees: 231,
  newHires: 18,
  avgSalary: 148500,
  departmentBreakdown: [
    { department: 'Engineering', count: 98,  avgSalary: 172000 },
    { department: 'Product',     count: 24,  avgSalary: 158000 },
    { department: 'Design',      count: 18,  avgSalary: 142000 },
    { department: 'Marketing',   count: 22,  avgSalary: 128000 },
    { department: 'Sales',       count: 31,  avgSalary: 118000 },
    { department: 'Operations',  count: 15,  avgSalary: 132000 },
    { department: 'Finance',     count: 12,  avgSalary: 145000 },
    { department: 'HR',          count: 10,  avgSalary: 112000 },
    { department: 'Legal',       count: 6,   avgSalary: 168000 },
    { department: 'Support',     count: 12,  avgSalary: 95000  },
  ],
  monthlyHires: [
    { month: 'Jan', count: 12 }, { month: 'Feb', count: 8  },
    { month: 'Mar', count: 15 }, { month: 'Apr', count: 11 },
    { month: 'May', count: 19 }, { month: 'Jun', count: 14 },
    { month: 'Jul', count: 9  }, { month: 'Aug', count: 22 },
    { month: 'Sep', count: 17 }, { month: 'Oct', count: 13 },
    { month: 'Nov', count: 20 }, { month: 'Dec', count: 18 },
  ],
  recentActivity: [
    { id: '1', type: 'HIRE',      message: 'New hire: Yuki Tanaka joined Engineering',           timestamp: new Date(Date.now() - 1000*60*30).toISOString(),        user: { id: '1',  name: 'Alex Chen',      avatar: undefined } },
    { id: '2', type: 'PROMOTION', message: 'Marcus Johnson promoted to Senior Engineer',         timestamp: new Date(Date.now() - 1000*60*120).toISOString(),       user: { id: '5',  name: 'David Kim',      avatar: undefined } },
    { id: '3', type: 'REVIEW',    message: 'Q4 performance reviews completed for Design team',   timestamp: new Date(Date.now() - 1000*60*240).toISOString(),       user: { id: '4',  name: 'Priya Patel',    avatar: undefined } },
    { id: '4', type: 'UPDATE',    message: 'Sarah Mitchell updated product roadmap',             timestamp: new Date(Date.now() - 1000*60*60*5).toISOString(),      user: { id: '2',  name: 'Sarah Mitchell', avatar: undefined } },
    { id: '5', type: 'NOTE',      message: 'Q1 hiring plan approved for Engineering',            timestamp: new Date(Date.now() - 1000*60*60*8).toISOString(),      user: { id: '10', name: 'Aria Foster',     avatar: undefined } },
  ],
  performanceMetrics: [
    { label: 'Retention Rate',    value: 94.2, change: 2.1,  trend: 'UP'      },
    { label: 'Engagement Score',  value: 8.7,  change: 0.3,  trend: 'UP'      },
    { label: 'Time to Hire',      value: 18,   change: -3,   trend: 'UP'      },
    { label: 'Offer Acceptance',  value: 87.5, change: -1.2, trend: 'DOWN'    },
  ],
}

export const SALARY_CHART_DATA = [
  { month: 'Jan', budget: 2800000, actual: 2650000 },
  { month: 'Feb', budget: 2800000, actual: 2720000 },
  { month: 'Mar', budget: 2900000, actual: 2880000 },
  { month: 'Apr', budget: 2900000, actual: 2950000 },
  { month: 'May', budget: 3000000, actual: 2980000 },
  { month: 'Jun', budget: 3000000, actual: 3100000 },
  { month: 'Jul', budget: 3100000, actual: 3050000 },
  { month: 'Aug', budget: 3200000, actual: 3220000 },
  { month: 'Sep', budget: 3200000, actual: 3180000 },
  { month: 'Oct', budget: 3300000, actual: 3280000 },
  { month: 'Nov', budget: 3400000, actual: 3350000 },
  { month: 'Dec', budget: 3500000, actual: 3480000 },
]
